### ISSUE TITLE
Add to microsoft live calendar not working

### ISSUE THREAD

**Issue by rochabianca** [nicolasbeauvais/vue-add-to-calendar#11]
Hello, when I click on add to microsoft live calendar (on my projects and on this doc) the only thing that they do is open a link to my calendar, but it didn't open any popups to add an event like what happen when you open the Google Calendar.

Edit: I just find out that there is a fix for this exact problem, but on the version 1.0.5 but the npm says that the last version is 1.0.4 even though you can see the v1.0.5 on the releases

**Comment by nicolasbeauvais** [comment]
Hello @rochabianca, thank you for raising the issue, I updated the package on npm!
